# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-19 02:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20160315_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewdepartment',
            name='code',
        ),
        migrations.RemoveField(
            model_name='interviewer',
            name='code',
        ),
        migrations.AlterField(
            model_name='boss',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interviewregister',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewRegister', to='user.InterviewDepartment'),
        ),
    ]
