# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20160819_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewee',
            old_name='matricNumber',
            new_name='hall',
        ),
        migrations.AddField(
            model_name='interviewee',
            name='matric_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
