# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20170218_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewee',
            name='exchange_this_semester',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewee',
            name='otherECA',
            field=models.CharField(default='', max_length=100),
        ),
    ]
