# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20170218_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewregister',
            name='experience',
            field=models.CharField(default='', max_length=500),
        ),
    ]
