# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_interviewregister_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewregister',
            name='experience',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
